### ISSUE TITLE
fields require attr logic error, can't save model

### ISSUE THREAD

**Issue by versionzhang** [gradam/django-better-admin-arrayfield#1]
* Django better admin ArrayField version: latest
* Django version:2.1.7
* Python version:3.7.3
* Operating System: Debian

### Description

Can't save model, I think there has a logic error.

https://github.com/gradam/django-better-admin-arrayfield/blob/0f3aa07d9a1ff03ac93f7d91750ef4826584a176/django_better_admin_arrayfield/forms/fields.py#L33

```
        if errors:
            raise forms.ValidationError(list(chain.from_iterable(errors)))
        if cleaned_data and self.required:
            raise forms.ValidationError(self.error_messages["required"])
        return cleaned_data
```
this line
```
      if cleaned_data and self.required:
```
should be
```
     if not cleaned_data and self.required:
```

**Comment by gradam** [comment]
Fixed in https://github.com/gradam/django-better-admin-arrayfield/commit/4ff331cf5b11f24e87e5573d36960802603a5773
Release 1.0.2
