### ISSUE TITLE
Incorrect behavior of widget, while trying to remove all items from arrayfield

### ISSUE THREAD

**Issue by Swojak-A** [gradam/django-better-admin-arrayfield#10]
* Django better admin ArrayField version: 1.0.2
* Django version: 2.2.3
* Python version: 3.7
* Operating System: python:alpine (from Dockerfile)

I have found incorrect behavior of widget, while trying to remove all items from arrayfield.

### Description

Assuming that: 
- I already have some items in arrayfield widget
- I want to have None

How to replicate incorrect behavior?
I click "x" button next to item for every item. Widget show no items. I click save and continue editing. Page is reloaded. The items are still there.

How to achieve correct behavior?
I click "x" button next to item for every item except last one. For the last item I clear the input field. Click save and continue editing. All items are gone.

**Comment by fjsj** [comment]
Reproduced this as well. As a user, I expect array to be saved as empty when I remove all items.
