### ISSUE TITLE
Improve template to make it look as the rest of Django Admin elements

### ISSUE THREAD

**Issue by javiermatos** [gradam/django-better-admin-arrayfield#119]
You can make the UI similar to the one Django Admin already has. I am mainly talking about the "Add another" button and the delete icon you are using.

```
{% load static %}
{% load i18n %}

{% spaceless %}
<div class="related-widget-wrapper">
    <div class="dynamic-array-widget">
        <ul>
            {% for subwidget in widget.subwidgets %}
                <li class="array-item" {% if widget.is_none %}data-isNone="true" style="display: none"{% endif %}>
                    {% with widget=subwidget %}
                        {% include widget.template_name %}
                    {% endwith %}
                    <div class="remove">
                        <div class="inline-deletelink"></div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div><input type="button" class="add-array-item" value="{% trans "Add another" %}"></div>
    </div>
</div>
{% endspaceless %}
```

I am basically using input instead of button, and using the built-in inline-deletelink image instead of the one you have.

Just by updating the template everything will work. I am running Django 3.1.

![Screenshot from 2020-12-08 16-46-06](https://user-images.githubusercontent.com/2723080/101506001-38b0cd80-3975-11eb-8268-47979d8f1cb8.png)

**Comment by gradam** [comment]
Hi

Thanks for the idea @javiermatos 

Do you feel like creating a PR with those changes?

**Comment by javiermatos** [comment]
Done in #120

**Comment by johncronan** [comment]
I'm using django-jazzmin here, and `<div class="inline-deletelink"></div>` displays nothing for me. FYI

I fixed it with some custom style. Perhaps some of this is just to be expected.
