### ISSUE TITLE
Remove Debug statements

### ISSUE THREAD

**Issue by SteinRobert** [gradam/django-better-admin-arrayfield#22]
### Description

In the `fields.py` is a print statement that could spam log files. It should be removed or replaced by `logger.debug`.

**Comment by ozandogrultan** [comment]
Hello, apparently this is fixed with https://github.com/gradam/django-better-admin-arrayfield/pull/16. Can you release a new version for it to take effect please? Thank you.

**Comment by gradam** [comment]
Fixed in 1.0.6
