### ISSUE TITLE
Display RadioSelect widget instead TextInput

### ISSUE THREAD

**Issue by KernelPan1k** [gradam/django-better-admin-arrayfield#24]
* Django better admin ArrayField version:
* Django version: 2.2.10
* Python version: 3.7
* Operating System: Linux

Hi,

I would like to know how to display a RadioSelect instead of a TextInput, can you help me?

Thanks

**Comment by gradam** [comment]
Hi @KernelPan1k, unfortunately, it is not currently possible but PRs are welcome!
