### ISSUE TITLE
Can't get 'DynamicArrayMixin' to import.

### ISSUE THREAD

**Issue by swawrzyn** [gradam/django-better-admin-arrayfield#3]
* Django better admin ArrayField version: 1.0.2
* Django version: 2.1.7
* Python version: 3.7
* Operating System: docker python:3.7-alpine

### Description

Trying to use your plug in to make my django admin arrayfields a bit more usable. I have a model where I'm using in conjunction with summernote. Maybe it's because I'm thick like crazy, but I can't get DynamicArrayMixin to work properly with my admin class. When I try to run my the django app using docker-compose all I get the following error:

class ListingAdmin(SummernoteModelAdmin, DynamicArrayMixin):
NameError: name 'DynamicArrayMixin' is not defined

I tried to define it any way I could, but I just couldn't get it to go.

Thanks for all your help.

**Comment by gradam** [comment]
Hi @swawrzyn 
Can you share your code that is failing?
And maybe it is a silly question but did you import the DynamicArrayMixin?

**Comment by swawrzyn** [comment]
Yeah, I took a look at the repo and got it to import like this:
>from django_better_admin_arrayfield.admin.mixins import DynamicArrayMixin

It's not throwing an error anymore, and here's my admin class:

> class ListingAdmin(SummernoteModelAdmin, DynamicArrayMixin):
    ordering = ['id']
    list_display = ['name']
    inlines = (AddressInline, ListingAmenityInline,)
    summernote_fields = ('description',)

While django throws no errors anymore, I'm not getting a change on the admin panel. The field continues to be the default comma delimited one.

**Comment by gradam** [comment]
Did you change the field in your model from standard Django ArrayField to `django_better_admin_arrayfield.models.fields.ArrayField` ?

**Comment by swawrzyn** [comment]
Awesome, that was it, everything works perfect now.

Dziękuję bardzo bracie, keep up the great work!
