### ISSUE TITLE
Admin saving None instead of empty array

### ISSUE THREAD

**Issue by fonar** [gradam/django-better-admin-arrayfield#50]
* Django better admin ArrayField version: 1.1.0
* Django version: 2.2.12
* Python version: 3.6
* Operating System: Windows

When i remove all elements from array in Django admin, it's saving None instead of empty array.

**Comment by sergei-maertens** [comment]
Probably related to #17 ?

**Comment by fonar** [comment]
> Probably related to #17 ?

@sergei-maertens Yes, it's the same issue. Why PR is not merged? this library is useless without it

**Comment by gradam** [comment]
Fixed in 16410c7
